services:
  - type: web
    name: medtime-backend
    env: docker
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/medTime-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080 